version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fuller
      - POSTGRES_PASSWORD=fuller
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: redis
    ports:
      - "6379:6379"
  localstack:
    container_name: "localstack"
    image: localstack/localstack-full
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data

    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
